#!/bin/bash
# Author - Fatma Elsayed
#About - Script to add group to the system

#Check if the user has root privilage
if [ $(id -u) -eq 0 ]
then
	while true; do
	group=$(whiptail --inputbox "Please Enter Group Name you want to add :" 10 40 --title "Add Group" 3>&1 1>&2 2>&3)
	if [ $? == 1 ]; then source ./main-menu; fi
        check=$(getent group $group | cut -d ":" -f1)  #check if the group exists

        if [ "$check" == "$group" ]
        then
            	if whiptail --title "Warning" --yesno "This Group $group already exists! , Do you want to try again ?" \
		 --yes-button "try again" --no-button "exit" 10 30; then
		       continue
                else
                        exit
                fi

        elif [ -z "$group" ]    #check if entered value = 0
        then
            	if whiptail --title "Error" --yesno "Empty Group Name , Do you want to try again ?" \
		 --yes-button "try again" --no-button "exit" 8 78; then
		       continue
                else
                        exit
                fi

        else
                groupadd  "$group"
                whiptail --title "Add Group Confirmation" --msgbox "Group $group has been added to the system successfully" 10 30
		break
        fi
	done
else
        whiptail --title "Warning !" --msgbox "Only root may add a user to the system." 10 30
fi


#check if user want to exit or return to main menu
if whiptail --yesno "Do you want to Return to main menu ?" --title "option" --yes-button "main menu" --no-button "Exit" 10 30; then
        source ./main-menu
else
        exit
fi

